### ISSUE TITLE
1.16.x and above hex colour formats break display

### ISSUE THREAD

**Issue by Ayymoss** [crashdemons/DisplayItem-Spigot#5]
Title, example: https://i.imgur.com/IThSRbV.png

Anything that's not using the old Minecraft colours gets converted to &0.

**Comment by crashdemons** [comment]
can you give an example of how you made the item?

**Comment by crashdemons** [comment]
also, it looks like this may be partly a spigot issue (as to why it appears black)
https://hub.spigotmc.org/jira/browse/SPIGOT-5829
supposedly it was fixed by a commit but possibly not fully. (are you up to date with the latest spigot?)

but when that is fixed, it will also probably need some advanced support in the plugin so that it appears styled at all.
this is because the item replacement uses
Spigot's [ItemMeta.getDisplayName](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#getDisplayName--) method
which is supposed to be the name of the item with formatting codes included.  There (probably?) arent formatting codes for the hex colors, so if the previous issue is fixed, the name **will probably appear white or uncolored/unstyled**.

to solve this properly, there needs to be an API method that can retrieve the ChatComponents of the item name, which isn't available in the Spigot-API that I can see.

But, I don't really get my hopes up about this being officially supported in Spigot because even the inbuilt chat event in spigot still only supports strings (no tags), The only way that this plugin is able to send messages with items is with the special [Player.Spigot Draft API method for sending component messages](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.Spigot.html#sendMessage-net.md_5.bungee.api.chat.BaseComponent...-) (which then cannot be seen by events).

**Comment by crashdemons** [comment]
![image](https://user-images.githubusercontent.com/3233238/85933397-301f7b80-b89c-11ea-89cd-232fc5d882ad.png)

27.06 18:33:24 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-6f4ff1b-983305b (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
27.06 18:33:24 [Server] Server thread/INFO Checking version, please wait...
27.06 18:33:24 [Server] Thread-112/INFO You are running the latest version


Correction: it seems to have a formatting code corresponding to the last letter of the hex color
#123456  was translated to &6 in getDisplayName
#12345a  was translated to &a in getDisplayName
seems there's still a bug

**Comment by Ayymoss** [comment]
I'll restart my server later today as I'm using some ancient version (2.4.1) see if that fixes anything.

After that, I'll let you know. 

But I use CMI for colour handling and the format is `{#FFFFFF}` which I used in an Anvil with some text. Printing `[item]` to chat returns the black item name.

**Comment by Ayymoss** [comment]
Decided to test on a different server, yep still broken.

As explained how I colour the items in-game it returns black item name. 

Using 2.6.0.

**Comment by crashdemons** [comment]
I imagine there is still a lot of difference between servers on how getDisplayName decides how to format things it can't possibly represent.

I'll have to research a lot into how to accomplish this specifically for DisplayItem.  In particular Spigot/Bukkit don't support hex colors [except in the bugeechat API](https://www.spigotmc.org/threads/spigot-bungeecord-1-16-1.447405/#post-3852349), while I have to get item names from the Bukkit API.  Getting the fully formatted name may require me to do some extra work with the item's NBT, which I generally avoid because it introduces version-specific dependencies/behavior.

I'm imagining it will work like this, hypothetically:
- prepare the chat message
- get the item meta
- perform normal macro replacements / formatting as in config
  - (new) if a new option (maybe something like `usenbtname`) is enabled, replace the displayname macro with a placeholder string
- complete macro replacements and all text-based formatting.
- (new) if a new option (maybe something like `usenbtname`) is enabled:
  - split the chat message into parts (before the placeholder, the placeholder, and after the placeholder)
  - translate the before and after parts into bungeechatcomponents and prepare for the middle part.
  - use reflection and read the NBT item name from NMS code. (hacky/not recommended)
  - somehow translate the NBT name into bungeechat components. (I'm not sure if/how this is possible or if I will have to resort to sending the entire message as NBT at this point which is even a more major change for the plugin).
  - use the translated item name components for the middle part.
  - assemble the new components into a BaseComponent array.
- (old) otherwise, translate the formatted chat message into a basecomponent
- combine all the components from the chat line formatting (username etc) into a single BaseComponent[]
- use Player.spigot().sendMessage to send the bungee-chat component message to everyone

As you can see there is a lot of work to be done for this, the other problem with this approach is NMS code can change a lot between versions so you have to make a decision:
- blindly attempt to support all versions 1.16+. (requires less maintenance but the plugin will break if Mojang changes anything significant with items/names).
- support specifically 1.16.1 and refuse to activate the feature for unsupported versions (requires making changes for every single minor version update to support it and you have to retain separate code for every version in the plugin, but it has less chance of breaking).

anyway not that any of this interesting to you, just planning ahead.   For now, there is no immediate fix possible to support hex colors wiithout considerable work, but if you want the item names to stop being black, you can negate/deny the _displayitem.colorname_ permission for regular users, which should prevent it from being having any color formatting at all aside from what you use in the config.

**Comment by crashdemons** [comment]
I've made an experimental edit to the plugin acf02476c493aa7ee2d2d3383865c2b079dd05b5 which works for me
a dev build is available here https://ci.meme.tips/job/DisplayItem-Spigot/21/

However, I still need to do testing to ensure that the new approach doesn't reintroduce a crash from items with too much NBT for chat, and then I need to remove debug lines that may spam the console when sharing an item.

**Comment by crashdemons** [comment]
While the above build works, it reintroduces the NBT limit issue.
Attempting to share a shulker box in chat with 11 custom-textured heads
 - before: no issue
 - after: 
```
04.07 18:49:32 [Server] Netty Epoll Server IO #1/WARN io.netty.handler.codec.EncoderException: String too big (was 66186 bytes encoded, max 32767)
04.07 18:49:32 [Server] Netty Epoll Server IO #1/WARN at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:332)
04.07 18:49:32 [Server] Netty Epoll Server IO #1/WARN at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:325)
04.07 18:49:32 [Server] Netty Epoll Server IO #1/WARN at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:32)
04.07 18:49:32 [Server] Netty Epoll Server IO #1/WARN at net.minecraft.server.v1_16_R1.PacketEncoder.encode(SourceFile:46)
04.07 18:49:32 [Server] Netty Epoll Server IO #1/WARN ... 34 more
```
since the hover event has to be set on each separate component of the name, it multiplies the size of the item...

**Comment by crashdemons** [comment]
dev build 22 should fix the remaining issues: https://ci.meme.tips/job/DisplayItem-Spigot/22/
but I recommend lowering your personal config's jsonlimit value to 8000

**Comment by Ayymoss** [comment]
Yep - This build works with CMI on my server. :)

Much appreciated.
